# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.1.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: 20302010026@fudan.edu.cn
author_name: Yi Shan
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_apod
mimetype: ''
mimetype_name: ''
project_short_description: Show a random NASA Astronomy Picture of the Day in a JupyterLab
    panel
python_name: jupyterlab_apod
repository: https://github.com/Shan-yi-shuai/Jupyterlab-Plugin-VNLI
test: true
viewer_name: ''

